import './globals.css'
import { Inter, Unbounded, JetBrains_Mono } from 'next/font/google'
import Header from '../components/Header';
import Cursor from '../common/Cursor';

const inter = Inter({ subsets: ['latin'], variable: '--font-body', display: 'swap' })
const unbounded = Unbounded({
  subsets: ['latin'],
  variable: '--font-display',
  display: 'swap',
  weight: '400',
})
const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
  weight: '400',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${inter.variable} ${unbounded.variable} ${jetbrainsMono.variable}`}
      >
        <Cursor />
        <Header />
        {children}
      </body>
    </html>
  )
}
